name: CI/CD

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Install .NET tools
        run: |
          dotnet tool install -g dotnet-ef --version 5.0.8
          dotnet tool install -g Microsoft.Web.LibraryManager.Cli --version 2.1.113
      - name: Install dependencies
        run: dotnet restore src
      - name: Install libs
        run: libman restore
      - name: Build
        run: dotnet build src -c Release --no-restore
#      - name: Test
#        run: dotnet test tests backend --no-restore --verbosity normal
      - name: Publish app
        run: dotnet publish src -c Release -o publish-artifacts/app --no-restore
      - name: Publish SQL script
        run: dotnet ef migrations script -i -p src -o publish-artifacts/sql/script.sql
      - name: Upload artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: publish-artifacts
          path: publish-artifacts
  DeployDev:
    if: github.event_name == 'push'
    runs-on: windows-latest
    needs: [Build]
    environment:
      name: Dev
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy Azure Resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./iac/main.bicep
        parameters: >
            appName=GigLocal
            env=Dev
            containerName=artists
            webAppSku=F1
            webAppSkuCapacity=1
            sqlAdminLogin=${{ secrets.AZURE_SQL_LOGIN }}
            sqlAdminPassword=${{ secrets.AZURE_SQL_PASSWORD }}
            sqlDatabaseName=GigLocal
            sqlDatabaseSku=Basic
            authGoogleClientId=${{ secrets.AUTH_GOOGLE_CLIENT_ID }}
            authGoogleClientSecret=${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }}
    - name: Set Deployment Outputs
      id: set_outputs
      run: |
        echo "::set-output name=websiteName::$($(az deployment group show -g GroupGigLocalDev -n main --query properties.outputs.websiteName.value) -replace '"', '')"
        echo "::set-output name=sqlServerName::$($(az deployment group show -g GroupGigLocalDev -n main --query properties.outputs.sqlServerName.value) -replace '"', '')"
        echo "::set-output name=sqlConnectionString::$($(az deployment group show -g GroupGigLocalDev -n main --query properties.outputs.sqlConnectionString.value) -replace '"', '')"
    - name: Download Publish Artifacts
      uses: actions/download-artifact@v2
    - name: Deploy SQL
      uses: azure/sql-action@v1
      with:
        server-name: ${{ steps.set_outputs.outputs.sqlServerName }}
        connection-string: ${{ steps.set_outputs.outputs.sqlConnectionString }}
        sql-file: publish-artifacts/sql/script.sql
    - name: Deploy Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.set_outputs.outputs.websiteName }}
        package: publish-artifacts/app
    - name: Logout of Azure
      run: az logout
